CREATE TABLE IF NOT EXISTS PERSON (
  PERSON_UUID UUID,
  FIRST_NAME VARCHAR(4096),
  LAST_NAME VARCHAR (4096),
  BIRTHDATE DATE,
);

CREATE TABLE IF NOT EXISTS RELATIONS (
  PERSON_UUID UUID,
  RELATIVE UUID,
  RELATION_TYPE VARCHAR(4096)
)